### ISSUE TITLE
Create Settings Page

### ISSUE THREAD

**Issue by TobiasHeimGalindo** [MatchUpDeployBuddy/MatchUp#18]
As a User I want a settings page to modify the notifications (on/off), login credentials (password), Help centre (some FAQ stuff for example) and the ability to invite friends to the app (friend code invite url).

Take inspiration from our Figma Design:
![image](https://github.com/user-attachments/assets/ba492c44-98e3-4ab0-bb3e-2790fc73b11b)

**Comment by CryPax** [comment]
Closed with #33
